### ISSUE TITLE
Missing Slides 😕

### ISSUE THREAD

**Issue by 3imed-jaberi** [TunisianJS/talks#20]
### TODO 🚀 

> close #3, #7, #9 and  #10 ..

__Talk 2:__
- [ ] React Native Fundamental By Mohamed Anouar Kotti.
- [ ] Playing with GraphQL using Apollo By Heithem Moumni.

__Talk 3:__
- [x] ZinkyJS framework 🇹🇳 By Burawi Ben Ammar. #24

__Talk 4:__
- [x] No Front-End Framework By Burawi Ben Ammar. #25 
- [x] Go Functional with Scala.js By Saddam Abu Ghaida. #26 
- [x] Lodash Library !! By Fares Karbia. #23 
- [ ] Functional Programming Fundamental By Zied Younes.

__Talk 5:__
- [x] Redux or Not to Redux By Medhat Dawoud. #21 

__Talk 6:__
 - [ ] Reactive Programming with RxJS By Saif Jerbi.
 
__Talk 7:__
 - [ ] Software Engineer life within a startup By Abdelwaheb Moalla.
 - [x] How to build a good software engineering career By Nebrass Lamouchi.
 - [ ] How technical decisions affect your project By Chehir Dhawedi.
 - [ ]  Managing a freelance career By Adnen Farhani.
 
ping @TunisianJS/core

**Comment by mnmajd** [comment]
I will look for it wait please ;) @3imed-jaberi

**Comment by heithemmoumni** [comment]
Ok

**Comment by sghaida** [comment]
hello, I pushed the slides and the [code here](https://github.com/sghaida/scala-js-demo)

**Comment by 3imed-jaberi** [comment]
> hello, I pushed the slides and the [code here](https://github.com/sghaida/scala-js-demo)
Thank you mr @sghaida  🚀 ..

**Comment by 3imed-jaberi** [comment]
ping @TunisianJS/core
